### PR TITLE
Suppress useless debugging prints (s/D = true/D = false/g)

### PR DESCRIPTION
**Pull request by angri**
Addresses https://bugs.launchpad.net/openquake/+bug/888013

### CODE REVIEW

**Comment by larsbutler** [comment]
FindBugs found a couple of issues:
- Test for floating point equality: https://github.com/gem/OpenSHA/blob/master/java/org/opensha/commons/data/function/ArbitrarilyDiscretizedFunc.java#L602
  - Can be replaced with `if (((Double)expY).equals(Double.MIN_VALUE))`
- invokes inefficient new Integer(int) constructor: https://github.com/gem/OpenSHA/blob/master/java/org/opensha/commons/data/function/ArbitrarilyDiscretizedFunc.java#L831
  - Can be replaced with `s.writeObject(getNum());`
- ArbitrarilyDiscretizedFunc.java also has a ton of commented-out code (line 608, line 939, etc.)
- Dead store to fltType: https://github.com/gem/OpenSHA/blob/master/java/org/opensha/sha/imr/attenRelImpl/Abrahamson_2000_AttenRel.java#L473
- Dead store to component: https://github.com/gem/OpenSHA/blob/master/java/org/opensha/sha/imr/attenRelImpl/Abrahamson_2000_AttenRel.java#L476
- Abrahamson_2000_AttenRel.java als has a ton of commented-out code.
- Unused variable f4: https://github.com/gem/OpenSHA/blob/master/java/org/opensha/sha/imr/attenRelImpl/Abrahamson_2000_AttenRel.java#L575
- Static field COMPONENT_AVE_HORZ should be accessed in a static way: https://github.com/gem/OpenSHA/blob/master/java/org/opensha/sha/imr/attenRelImpl/Abrahamson_2000_AttenRel.java#L884 and https://github.com/gem/OpenSHA/blob/master/java/org/opensha/sha/imr/attenRelImpl/Abrahamson_2000_AttenRel.java#L888
- Static field COMPONENT_AVE_HORZ should be accessed in a static way: https://github.com/gem/OpenSHA/blob/master/java/org/opensha/sha/imr/attenRelImpl/CB_2003_AttenRel.java#L822
- Should org.opensha.sha.imr.attenRelImpl.CB_2003_AttenRel$CB_2003_AttenRelCoefficients be a _static_ inner 
  class?
- Method org.opensha.sha.imr.attenRelImpl.Campbell_1997_AttenRel.getStdDev() uses the same code for two 
  branches: https://github.com/gem/OpenSHA/blob/master/java/org/opensha/sha/imr/attenRelImpl/Campbell_1997_AttenRel.java#L603
- Should org.opensha.sha.imr.attenRelImpl.Campbell_1997_AttenRel$Campbell_1997_AttenRelCoefficients be a _static_ inner 
  class?

**Comment by larsbutler** [comment]
- Dead store to component: https://github.com/gem/OpenSHA/blob/master/java/org/opensha/sha/imr/attenRelImpl/SadighEtAl_1997_AttenRel.java#L303
- Should org.opensha.sha.imr.attenRelImpl.SadighEtAl_1997_AttenRel$SCEMY_1997_AttenRelCoefficients be a _static_ inner 
  class?
- Unused imports: https://github.com/gem/OpenSHA/blob/master/java/org/opensha/sha/imr/param/PropagationEffectParams/DistanceX_Parameter.java#L22, https://github.com/gem/OpenSHA/blob/master/java/org/opensha/sha/imr/param/PropagationEffectParams/DistanceX_Parameter.java#L33
- Unused commented-out code: https://github.com/gem/OpenSHA/blob/master/java/org/opensha/sha/imr/param/PropagationEffectParams/DistanceX_Parameter.java#L296

**Comment by larsbutler** [comment]
I won't force you to do these cleanups, but since the files are being touched we might as well do some house cleaning.

**Comment by angri** [comment]
I agree with all that concerns. I'm just afraid these are a bit out of scope for bug 888013. Could you please report another bug to address those problems?

**Comment by larsbutler** [comment]
Sure, I can do that.

LGTM.

**Comment by larsbutler** [comment]
Reported the other issues as a separate bug: https://bugs.launchpad.net/openquake/+bug/894040

**Pull request merged**
